spring:
  profiles:
    active: local
  application:
    name: vibe-pay-api

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vibepay
    username: postgres
    password: postgres
  session:
    store-type: none

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.vibepay.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080
  servlet:
    context-path: /

# PG 결제 설정
payment:
  inicis:
    mid: INIpayTest
    signKey: SU5JTElURV9UUklQTEVERVNfS0VZU1RS
    iniApiKey: ItEQKi3rY7uvDS8l
    hashKey: 3CB8183A4BE283555ACC8363C0360223

# 토스페이먼츠 설정
toss:
  client-key: ${TOSS_CLIENT_KEY:test_ck_DpexMgkW36PL5OnYYn7drGbR5ozO}
  secret-key: ${TOSS_SECRET_KEY:test_sk_P9BRQmyarY56W4lPgbnNrJ07KzLN}

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stg

---
spring:
  config:
    activate:
      on-profile: cbo

---
spring:
  config:
    activate:
      on-profile: prod
